### ISSUE TITLE
Archr2Signac without peakMatrix

### ISSUE THREAD

**Issue by Guliariel** [swaruplabUCI/ArchRtoSignac#17]
Hi,
Thank you for creating this package. 
I am working on CUT&tag data and I am not using the ArchR peak calling method. 
I was wondering if I can convert my ArchR project into a Seurat object without using the getPeakMatrix?

Thank you very much

**Comment by rootze** [comment]
> CUT&tag data

Hello, @Guliariel Thanks for considering ArchR2Signac. I have never worked on CUT&tag data before, assuming this is also single-cell CUT&tag. Do you have an ArchRproject made from single cell CUT&tag raw data? Ideally, it would work even if you don't have a peak matrix as long as you provide a count matrix for constructing Signac Objects.

**Comment by rootze** [comment]
> Thank you for your reply. Unfortunately it does not work me. I was trying to use : pkm <- getMatrixFromArrow(....)/getMatrixFromProject() in order to extract the count matrix (from ArchR). I receive this error: Error in `separate()`: ! Can't extract columns that don't exist. ✖ Column `ranges` doesn't exist. Run `rlang::last_error()` to see where the error occurred.
> 
> I would appreciate if any solution will be suggested. Thank you

Hello @Guliariel, The error means you don't have the matrix you intended to extract. `getMatrixFromArrow(....)/getMatrixFromProject()` are two functions in ArchR. However, with the information you provided, I am not sure what you ran. Please provide more details. 

Also, if you can, please provide the returns for this function `getAvailableMatrices(Your_ArchRproject)`. I would like to know what available matrices you have 

I have never worked on CUT&tag data before, so the more information/code regarding how you process your data into ArchR, the better it will help me to help you solve the problem you have.

**Comment by rootze** [comment]
> getAvailableMatrices(pooledATAC)
> [1] "GeneScoreMatrix" "TileMatrix"

Hello @Guliariel I see your `pooledATAC` doesn't have a peak matrix.  Signac needs a `peakmatrix`, and its format is different from `tilematrix` in ArchRProject. So you need to finish the [Calling Peaks with ArchR](https://www.archrproject.com/bookdown/calling-peaks-with-archr.html) step and have a `peakmatrix` in ArchRProject before using `ArchR2Signac()` conversion. Please see the detailed steps in our [STAR protocol](https://www.sciencedirect.com/science/article/pii/S2666166722003719?via%3Dihub) regarding the order of the steps. And also please be aware that our package has been updated, so please refer to the [README](https://github.com/swaruplabUCI/ArchRtoSignac#readme) for detailed usage of certain functions. 

And out of curiosity, are your fragments files from cellranger output?  if not, make sure you have the correct format by changing the `fragments_file_extension`. 

I hope this might help you. Please let me know whether it works or not. Thank you!

**Comment by rootze** [comment]
@Guliariel I apologize for my delayed response and for any confusion my previous message may have caused. I understand now that you do not want to use the ArchR peak calling method but still wish to perform the conversion. This is a new request for me, and I appreciate you bringing it to my attention.

To clarify, it is possible to create a Seurat object from scratch even without using the `ArchR2Signac()` function. This is how we made the `ArchRtoSignac` package. However, please note that the data must be organized separately in this case. If you need any assistance with this process, please let me know, and I will do my best to help you.

Thank you for reaching out to me, and please don't hesitate to ask if you have any further questions.

**Comment by Guliariel** [comment]
Thank you for your answer.
I would appreciate if you could help me with that. 
Since the way I need to call peak is unique I will not be able to use the ArchR neither the Signac peak calling and therefore I am looking for a way that I can create a Seurat object without using this matrix if it is even possible. 
Would appreciate to hear your comment about this thought. 

Thank you

**Comment by rootze** [comment]
> the way I need to call peak is unique

Well, this is not an easy task, to be honest. I am not sure what you need to use to call peaks (if you can share that method or paper, so I can read about it, maybe it would be better), but what you need to use that method to get a raw or normalized count matrix at least ---- peaks by cells matrix... hope this is doable in your case...

**Comment by rootze** [comment]
Issue closed due to inactivity, but feel free to reopen it if needed
