### ISSUE TITLE
Error in h5checktypeOrOpenLoc()

### ISSUE THREAD

**Issue by Yiqa** [swaruplabUCI/ArchRtoSignac#19]
Hi, thank you for creating this package.
I got Error in h5checktypeOrOpenLoc(file, readonly = TRUE, fapl = NULL, native = native): Error in h5checktypeOrOpenLoc(). Cannot open file. File '/data/proj/GCB_FBP/human_dev/exploratory/hca_dev_best3/ArrowFiles/HES1.arrow' does not exist.
Traceback:

1. getPeakMatrix(proj)
2. ArchR::getMatrixFromProject(ArchRProject, useMatrix = "PeakMatrix")
3. getAvailableMatrices(ArchRProj)
4. .availableArrays(getArrowFiles(ArchRProj = ArchRProj))
5. .safelapply(seq_along(ArrowFiles), function(x) {
 .     groups <- h5ls(ArrowFiles[x]) %>% {
 .         .[.$group == "/" & .$otype == "H5I_GROUP", "name"]
 .     }
 .     groups <- groups[!grepl("Fragments|Metadata", groups)]
 .     groups
 . }, threads = threads) %>% Reduce("intersect", .)
6. Reduce("intersect", .)
7. .safelapply(seq_along(ArrowFiles), function(x) {
 .     groups <- h5ls(ArrowFiles[x]) %>% {
 .         .[.$group == "/" & .$otype == "H5I_GROUP", "name"]
 .     }
 .     groups <- groups[!grepl("Fragments|Metadata", groups)]
 .     groups
 . }, threads = threads)
8. lapply(...)
9. FUN(X[[i]], ...)
10. h5ls(ArrowFiles[x]) %>% {
  .     .[.$group == "/" & .$otype == "H5I_GROUP", "name"]
  . }
11. h5ls(ArrowFiles[x])
12. h5checktypeOrOpenLoc(file, readonly = TRUE, fapl = NULL, native = native)
13. stop("Error in ", fctname, ". Cannot open file. File '", file, 
  .     "' does not exist.")

Could you help me with this?

**Comment by rootze** [comment]
@Yiqa Thanks for using ArchRtoSignac. I'm not sure which function you are running? More information, including what you run and provided in that function would be better for me to understand what could potentially cause the error. Thank you!

**Comment by Yiqa** [comment]
Hi, thank you for your reply,  sorry for unclear question.

When I run the step to obtain ArchRProject peak matrix for object conversion.

```r
proj <- readRDS("home/private/archr_proj.rds")
pkm <- getPeakMatrix(proj)
``` 
I got the error as shown in the above conversation

**Comment by rootze** [comment]
> ```r
> proj <- readRDS("home/private/archr_proj.rds")
> ```

Hello @Yiqa 

Did you call peakMatrix in your ArchRProject?  
Please run the following code and let me know. I wonder what matrix you have in your data. 
```r
getAvailableMatrices(proj)
```
If you don't have a peak matrix in your ArchRProject, you have to proceed to the step `calling-peaks-with-archr` https://www.archrproject.com/bookdown/calling-peaks-with-archr.html

ArchR handles the peak calling approach and stores the data differently than Signac, and we argued that you need to finish the peak calling steps before successfully transferring it to Signac.

**Comment by Yiqa** [comment]
@rootze Hi, sorry for late reply. 
When I run  `getAvailableMatrices(proj)`

I get an error:
Error in h5checktypeOrOpenLoc(file, readonly = TRUE, fapl = NULL, native = native): Error in h5checktypeOrOpenLoc(). Cannot open file. File '/data/proj/GCB_FBP/human_dev/exploratory/hca_dev_best3/ArrowFiles/HES1.arrow' does not exist.

It seems that I don't have a peak martix in my ArchRProject, I am a bit new to use ArchR, thank you for your guidance, I will try your suggestions.

**Comment by rootze** [comment]
> When I run `getAvailableMatrices(proj)`
> 
> I get an error: Error in h5checktypeOrOpenLoc(file, readonly = TRUE, fapl = NULL, native = native): Error in h5checktypeOrOpenLoc(). Cannot open file. File '/data/proj/GCB_FBP/human_dev/exploratory/hca_dev_best3/ArrowFiles/HES1.arrow' does not exist.

Hello @Yiqa 
I suspect that your ArchRProject has no peak matrix. But by running a function from ArchR package `getAvailableMatrices(proj)`. This error tells me there is something wrong with your sample arrow file HES1
`/data/proj/GCB_FBP/human_dev/exploratory/hca_dev_best3/ArrowFiles/HES1.arrow`. 

Do all your samples have arrow files beside HES1? You may want to double-check if there are errors when you `createArrowFiles`. Please let me know. Thank you!

**Comment by rootze** [comment]
@Yiqa Closed due to GitHub issue inactivity. Feel free to reopen if needed.
