### ISSUE TITLE
Error in CreateFragmentObject 

### ISSUE THREAD

**Issue by Larrycpan** [swaruplabUCI/ArchRtoSignac#2]
Thanks for the contribution. I run the `ArchR2Signac` function and get the error 
`Error in CreateFragmentObject(path = fragments, cells = cells, validate.fragments = validate.fragments,  : Fragment file does not exist.` 
There is only one fragment.tsv.gz in the folder, and I provide the full path to the parameter `fragments_dir`. How to fix it?
Thanks!

**Comment by rootze** [comment]
> Thanks for the contribution. I run the `ArchR2Signac` function and get the error `Error in CreateFragmentObject(path = fragments, cells = cells, validate.fragments = validate.fragments, : Fragment file does not exist.` There is only one fragment.tsv.gz in the folder, and I provide the full path to the parameter `fragments_dir`. How to fix it? Thanks!

@KeWXiong Thanks for using ArchR2Signac. If this problem is not resolved yet, would you mind providing an example of your `fragments_dir`? So I can help you figure out the problem! Thank you!

**Comment by rootze** [comment]
Hello @KeWXiong 
I'm not sure if you are still using this package. But it seems that Issue #3 has a similar problem as you, so I have updated the package to solve the problem. Let me know if you need help with yours. Thank you!

**Comment by rootze** [comment]
Closed due to lack of response from reporter
