### ISSUE TITLE
Customized UMAP name and IterativeLSI request

### ISSUE THREAD

**Issue by Sky970415** [swaruplabUCI/ArchRtoSignac#20]
Hi @rootze,
Could you please change the addDimRed() with customized UMAP names and IterativeLSI names? 
Sometimes the name for those are not default. If you could use `[[addUMAPs]]` instead of the hard coded `$`, it would be great.

Thanks,
Jiakang

**Comment by rootze** [comment]
@Sky970415 Hello Jiakang, 
Thanks for using the ArchRtoSignac package and making a great suggestion. I am currently on vacation, so I won't be able to help you promptly. If you want to create an additional function, `addcustomizedDimRed()`, and create a pull request, I am more than happy to pull it and make it a part of this package. Thank you!

**Comment by rootze** [comment]
@Sky970415 Hello Jiakang. Thanks for creating the pull request. I will review the code and pull the request later. I'm in the midst of another project, so please allow me a week or so to finish the testing. Thank you again.

**Comment by rootze** [comment]
Request pulled, issue closed, thank you.
