### ISSUE TITLE
Checking for 11858 cell barcodes [1] "In Progress:" [1] "Merge Seurat list" Error in validObject(object = .Object) :    invalid class "Seurat" object: all assays must have a key

### ISSUE THREAD

**Issue by Weiming113** [swaruplabUCI/ArchRtoSignac#24]
Could you please help resolve this issue?

Computing hash
Checking for 5432 cell barcodes
[1] "Run_04_24h"
[1] 165939  11858
Computing hash
Checking for 11858 cell barcodes
[1] "In Progress:"
[1] "Merge Seurat list"
Error in validObject(object = .Object) : 
  invalid class "Seurat" object: all assays must have a key

**Comment by rootze** [comment]
Hello @Weiming113, ideally, when reporting an error, it would be better if you could share which version your Signac, Seurat, and other necessary packages are in. 

But as far as I understand, from your error message, this is a Seurat and Signac package version problem. Please see the following issue on https://github.com/satijalab/seurat/issues/7631.
