### ISSUE TITLE
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  :    'data' must be of a vector type, was 'NULL'

### ISSUE THREAD

**Issue by sylestiel** [swaruplabUCI/ArchRtoSignac#31]
@rootze @Sky970415 

> seurat_atac <- addDimRed(
+   ArchRProject = proj,
+   SeuratObject = seurat_atac,
+   addUMAPs = "UMAP",
+   reducedDims = "IterativeLSI"
+ ) # default is "IterativeLSI"
[1] "In Progress:"
[1] "add UMAP From ArchRProject to SeuratObject"
###  'data' must be of a vector type, was 'NULL'

How may I fix this problem?

**Comment by rootze** [comment]
@sylestiel Thanks for using the ArchRtoSignac package. The error message you provided is a bit limited, and the specific cause of the error may depend on various factors within your code and data.
Here are some possible reasons for the error:
**Data Compatibility**: The data in your seurat_atac object may not be in the expected format or structure for dimensionality reduction. Would you mind showing the steps that you used to create your `seurat_atac`
**Incompatible Parameters**: The parameters you're passing to addDimRed might be causing issues. In this case, you're specifying addUMAPs = "UMAP" and reducedDims = "IterativeLSI". It's possible that the combination of these parameters is not appropriate for your data.
The more code and steps that you can share with us. The better we can help you out in solving this error.

**Comment by sylestiel** [comment]
Hi @rootze,

The ArchR project was obtained from two multiome samples processed together. 

The code so far is as follows:

```{r}
# install ArchRtoSignac
#devtools::install_github("swaruplabUCI/ArchRtoSignac")
library(ArchR)
# load ArchRtoSignac
library(ArchRtoSignac)
```

```{r}
packages <- c("ArchR","Seurat", "Signac","stringr") # required packages
loadinglibrary(packages)

```

```{r STEP 1 - Obtain ArchRProject peak matrix for object conversion.}
proj <- readRDS("~/Desktop/R_projects/ArchR/Save-Proj4-Dual_Merged/Save-ArchR-Project.rds")
getAvailableMatrices(proj)
pkm <- getPeakMatrix(proj) # proj is an ArchRProject

```

```{r STEP 2 - Extract appropriate Ensembl gene annotation and convert to UCSC style.}
library(EnsDb.Mmusculus.v79)
annotations <- getAnnotation(reference = EnsDb.Mmusculus.v79, refversion = "mm10")
```
```{r STEP 3 - Convert ArchRProject to Signac SeuratObject.}
fragments_dir <- list(
  "Filepath/Multiome_sample_1/outs/atac_fragments.tsv.gz, /FilepathMultiome_sample_2/outs/atac_fragments.tsv.gz "
  
)
seurat_atac <- ArchR2Signac(
  ArchRProject = proj,
  refversion = "mm10",
  fragments_dir = fragments_dir,
  pm = pkm, 
  fragments_fromcellranger = "NO", 
  fragments_file_extension = NULL, 
  annotation = annotations)


```

```{r STEP 4 - Transfer ArchRProject gene score matrix to Signac SeuratObject.}
gsm <- getGeneScoreMatrix(ArchRProject = proj, SeuratObject = seurat_atac)

seurat_atac[['RNA']] <- CreateAssayObject(counts = gsm)

```

```{r STEP 5 - Transfer ArchRProject dimension reduction }
seurat_atac <- addDimRed(
  ArchRProject = proj,
  SeuratObject = seurat_atac,
  addUMAPs = "UMAP",
  reducedDims = "IterativeLSI"
) 
```

The error is encountered at the addDimRed step.

Would appreciate your suggestion.

Thanks!

**Comment by rootze** [comment]
Hello @sylestiel, looking through your code, I didn't see any problem that could give me a hint of why it didn't work. The hardest part, which is `ArchR2Signac`. 

### ERROR reported above
> * [1] "In Progress:"
>   [1] "add UMAP From ArchRProject to SeuratObject"

It seems to me that it stopped at the extraction of UMAP steps in the source code. So please let me know if the following code works or not. Thanks

```
  umap_df <- Your_ArchRProject@embeddings$UMAP$df %>% as.matrix
  rownames(umap_df) <- colnames(Your_SeuratObject) # make the rowname the same format as seurat
  colnames(umap_df) <- c('UMAP_1', 'UMAP_2')

  Your_SeuratObject@reductions$umap <- Seurat::CreateDimReducObject(
      embeddings=umap_df,
      assay="peaks"
  )
```

**Comment by sylestiel** [comment]
Hi @rootze,

 That did not address the issue. The sample problem persists. Would the fact that my project has 3 separate UMAPs pose a problem?

I have UMAP_ATAC, UMAP_RNA, and UMAP_Combined.

Thanks!

**Comment by rootze** [comment]
> I have UMAP_ATAC, UMAP_RNA, and UMAP_Combined.

Hello @sylestiel yes, that's the problem. Please use update ArchRtoSignac package to the lastest version, and use the `addCustomizeDimRed` function as shown in the end of README. Please add one UMAP at a time. Let me know if that works or not.

**Comment by sylestiel** [comment]
@rootze,

 should I still add the umap_df command as you suggest earlier?
Also, the package installed is v 1.0.3

That I believe is the latest.

**Comment by rootze** [comment]
> seurat_atac[['RNA']] <- CreateAssayObject(counts = gsm)

@sylestiel Do you have a muti-ome or only snATAC-seq data in this ArchRObject? I have yet to deal with multi-ome before. Do you have a UMAP ATAC (for scATAC) and then UMAP RNA (for scRNA or your imputed gene activity)? You don't need to use the `umap_df command ` I showed you before. I was checking if your UMAP exists, and yes, they do, but in a different name.

**Comment by sylestiel** [comment]
Yes it is multiome datasets (ATAC+RNA) Merged using ArchR.

**Comment by rootze** [comment]
> Yes it is multiome datasets (ATAC+RNA) Merged using ArchR.

Oh, great! Again, as I mentioned in my last comment. I have yet to deal with a multi-ome. And I also want to emphasize if you have a multi-ome, please be aware if you want to name your imputed gene activity here as RNA in your code above seurat_atac[['RNA']] <- CreateAssayObject(counts = gsm). It may have conflicting problems with your TRUE scRNA-seq data, whose assay is often named as `RNA`.  One more thing;`addCustomizeDimRed` only works on `UMAP` or `reducedDimsType = 'IterativeLSI'`. `IterativeLSI` is what people normally use for snATAC-seq. I am not sure what `reducedDimsType` you have for the scRNA-seq and how they are stored in ArchRObject. But you can definitely extract them and add them to the new Seurat object separately after the data conversion `ArchR2Signac`.

**Comment by rootze** [comment]
Issue closed due to inactivity, but feel free to reopen it if needed
