### ISSUE TITLE
 ArchR2Signac - Merging Seurat list

### ISSUE THREAD

**Issue by laurajohanne** [swaruplabUCI/ArchRtoSignac#34]
Hi, 
Great packaged very helpful package! I was able to use the package successfully in November (with seurat v. 4.4.0).
But now when I try to re-run the code I get the error;

[1] "In Progress:"
[1] "Merge Seurat list"
Error in rep(yes, length.out = len): attempt to replicate an object of type 'S4'
Traceback:

1. ArchR2Signac(ArchRProject = ArchRPro, refversion = "mm10", samples = samples, 
 .     fragments_dir = fragments_dir, pm = pm, fragments_fromcellranger = "Yes", 
 .     annotation = annotations, )
2. ifelse(length(seurat_list) > 1, merge(x = seurat_list[[1]], y = seurat_list[2:length(seurat_list)], 
 .     add.cell.ids = samples), seurat_list[[1]])

When running:
seurat_atac <- ArchR2Signac(
  ArchRProject = ArchRPro,
  refversion = "mm10",
  samples = samples,
  fragments_dir = fragments_dir,
  pm = pm,
  fragments_fromcellranger = "Yes",
  annotation = annotations,
)

Both when I use Seurat v. 5 and  Seurat v.4.4.0.
ArchRtoSignac v.1.0.3

I wonder if it has something to do with the new function for merging in the ArchR2Signac function but I am not sure. 

Thanks in advance.

Best regards, 
Laura

**Comment by rootze** [comment]
Hi, @laurajohanne . Thank you so much for using the ArchRtoSignac package. Yes, the Error was due to a recent update. I have fixed the code and test on the PBMC dataset. Please try it again on your data and let me know if it works on your end or not. Also, when you update, try not to use Seurat V5 at this stage. We are actively trying to work on this and other packages to incorporate all the supporting packages work with V5. The current version of ArchRtoSignac should be ArchRtoSignac_1.0.4. Thank you once again!

**Comment by laurajohanne** [comment]
Thank you so much for your fast reply! Sorry it has taken me some time to get back to you.

I got it to work on my data, thank you very much for your help.

Version of package:
ArchRtoSignac v.1.0.4

Versions of required dependencies:
biovizBase v.1.50.0
ArchR  v.1.0.2
Signac v.1.12.0
Seurat v.4.4.0
stringr v.1.5.1

Thanks again for a great package!

**Comment by peggiechien** [comment]
Hello, I was having the same issue as @laurajohanne described in this post and I've updated my packages and dependencies to be the same versions as @laurajohanne described in the previous comment. However, I'm running into this error now (I am using hg38 instead of mm10):

Error in download.file(url, destfile, quiet = TRUE) : 
cannot open URL 'https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'

Please let me know how I should proceed.

Thank you!

**Comment by rootze** [comment]
Hello @peggiechien, Thanks for using the ArchRtoSignac package. I see the error is not directly due to the ArchRtoSignac package. But if you want to share the code you ran till the function when the error occurred here, I may be able to help you. Thank you

**Comment by peggiechien** [comment]
Hi @rootze ,

Thank you for helping. I ran the code to convert the ArchR project to a Signac SeuratObject:

seurat_atac <- ArchR2Signac(
  ArchRProject = proj,
  refversion = "hg38",
  samples = proj@cellColData$Sample,
  fragments_dir = fragments_dir,
  pm = pkm, # peak matrix from getPeakMatrix()
  fragments_fromcellranger = "NO", # fragments_fromcellranger This is an Yes or No selection ("NO" | "N" | "No" or "YES" | "Y" | "Yes")
  fragments_file_extension = ".fragments.tsv.gz", # Default - NULL: File_Extension for fragments files (typically they should be '.tsv.gz' or '.fragments.tsv.gz')
  annotation = annotations # annotation from getAnnotation()
)

And here is the output from that:

[1] "IF selecting NO, please make sure to provide fragments_file_extension"
[1] "In Progress:"
[1] "Prepare Seurat list for each sample"
[1] "PCJ01"
[1] 247814    312
Computing hash
Checking for 312 cell barcodes
Error in download.file(url, destfile, quiet = TRUE) : 
cannot open URL 'https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'

Here is some of the traceback that led to the error message:

22.
download.file(url, destfile, quiet = TRUE)
21.
withCallingHandlers(expr, warning = function(w) if (inherits(w, 
classes)) tryInvokeRestart("muffleWarning"))
20.
suppressWarnings(download.file(url, destfile, quiet = TRUE))
19.
fetch_table_from_url(url, colnames = names(col2class), col2class = col2class)
18.
fetch_table_from_UCSC_database(genome, "chromInfo", col2class = col2class, 
goldenPath.url = goldenPath.url)
17.
.fetch_chrom_sizes_from_UCSC_database(genome, goldenPath.url = goldenPath.url)
16.
GenomeInfoDb:::fetch_chrom_sizes_from_UCSC(GENOME, goldenPath.url = goldenPath.url) at hg38.R#65

Please let me know if you need any other information.

**Comment by rootze** [comment]
@peggiechien Hello, one quick question, did you install and load this R library (`EnsDb.Hsapiens.v86`) ?
Is there any error when you try to run the following code? 

```
library(EnsDb.Hsapiens.v86) # Ensembl database to convert to human hg38. Install what is appropriate for your analysis

annotations <- getAnnotation(reference = EnsDb.Hsapiens.v86, refversion = "hg38") # "UCSC" is the default style to change to but can be changed with argument seqStyle
```

**Comment by peggiechien** [comment]
The `EnsDb.Hsapiens.v86` library loads with no issues.

When I ran the getAnnotation() line, it came out with this:

[1] "In Progress:"
[1] "Extract genomic ranges from EnsDb object and prepare annotation"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 21s
Error in download.file(url, destfile, quiet = TRUE) : 
cannot open URL 'https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'

This ran fine before so the error is new.

**Comment by rootze** [comment]
Hello @peggiechien 

Just minutes ago, I tried to run this code as well. It worked at my end, so, unfortunately, I was able to reproduce your error. 
But here is my libraries to run the code. 
```
other attached packages:
 [1] EnsDb.Hsapiens.v86_2.99.0 ensembldb_2.22.0
 [3] AnnotationFilter_1.22.0   GenomicFeatures_1.50.4
 [5] AnnotationDbi_1.60.0      Biobase_2.58.0
 [7] GenomicRanges_1.50.2      GenomeInfoDb_1.34.9
 [9] IRanges_2.32.0            S4Vectors_0.36.1
[11] BiocGenerics_0.44.0       ArchRtoSignac_1.0.4
```
Maybe you can try the following code from Signac? 
```
# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)

# change to UCSC style since the data was mapped to hg38
seqlevels(annotations) <- paste0('chr', seqlevels(annotations))
genome(annotations) <- "hg38"
```

Also, through a random search:  https://github.com/stuart-lab/signac/issues/1619
Internet problem??? 

Let me know 
Thank you

**Comment by peggiechien** [comment]
Hi @rootze , I tried both your suggestions and it works now! Thank you so much for the help and for this package!

**Comment by rootze** [comment]
@peggiechien Great! Once again, thank you so much for using the ArchRtoSignac package. If you can, please cite this package, which will greatly help and motivate us to develop other useful packages. I just wanted to let you know that our team has another useful ATAC-seq package coming up soon so you can stay in tune. Thank you!
