### ISSUE TITLE
Signac to ArchR?

### ISSUE THREAD

**Issue by hcjarnagin** [swaruplabUCI/ArchRtoSignac#38]
Hi, I was wondering if it was possible to convert an Signac/Seurat object to ArchR? I've already performed all my clustering in Signac, but there are some functions of ArchR I'd love to test on this data. 

Any advice you have would be great! 
Thank you!

**Comment by rootze** [comment]
@hcjarnagin, I am not aware of that conversion, nor is that doable. Our package only converts objects from ArchR to Signac. Thank you.

**Comment by FrankSurrey5** [comment]
> Hi, I was wondering if it was possible to convert an Signac/Seurat object to ArchR? I've already performed all my clustering in Signac, but there are some functions of ArchR I'd love to test on this data.
> 
> Any advice you have would be great! Thank you!

Hi, I also want to convert my Seurat object to ArchR. Did you solve that?

**Comment by alifarhat40** [comment]
Hi @hcjarnagin have you figured out a way to achieve this? I am also trying to convert a signac seurat object (multimodal) to a ArchR object.
