### ISSUE TITLE
 A bug about the sample name

### ISSUE THREAD

**Issue by hydraphenix** [swaruplabUCI/ArchRtoSignac#39]
Thank you for your package!

I've found a little bug in function ArchR2Signac.
When I have two samples like 'OA1' and 'NOA1', I got the error information "Not all cells requested could be found in the fragment file.".

When I change the code in the function like below, that will be good.
`cur_pm <- pm[, grepl(paste0(cur_sample, "#"), colnames(pm))]`
should be
`cur_pm <- pm[, grepl(paste0('^',cur_sample, "#"), colnames(pm))]`

**Comment by rootze** [comment]
Package Update V1.0.5

**Comment by rootze** [comment]
@hydraphenix Thanks for catching that. Bug fixed with Package Update V1.0.5
