### ISSUE TITLE
Container support

### ISSUE THREAD

**Issue by Leon-Bichmann** [swaruplabUCI/ArchRtoSignac#40]
Hi,
Would be great to have this available as a pre-built container - could you provide something like this?

**Comment by rootze** [comment]
@Leon-Bichmann Thanks for being interested in using ArchtoSignac. As for pre-built containers, are you referring docker or singularity? Currently, I don't support container building

**Comment by Leon-Bichmann** [comment]
Hi ok no worries then I found a workaround - thx for the reply
